module Website.Tags

let tags =
    [
        "accordion"
        "canvas"
        "chart"
        "connectivity"
        "dom"
        "drag drop"
        "fsharp"
        "geolocation"
        "google"
        "html"
        "html5"
        "javascript"
        "jquery"
        "jquery ui"
        "kendo ui"
        "location"
        "map"
        "multimedia"
        "rpc"
        "twitter"
        "video"
        "visualization"
        "websharper"
        "websocket"
        "widget"
        "window"
    ]